### ISSUE TITLE
Continously increasing memory usage after migrating to Netherite

### ISSUE THREAD

**Issue by martinhenrysson** [microsoft/durabletask-netherite#160]
We migrated one of our production services to Netherite after successful testing of the preview version in our non-production environment. However, after deploying to production we notice that the memory working set is increasing all the time making me fear that we'll run out of memory in the app service plan if the service would be left unattended (restarting the function app helps as you can see).

![image](https://user-images.githubusercontent.com/35069050/169483460-91b22479-cb29-4c64-b926-ef30b21d574f.png)

The workload is much higher in production than in our other environments, but I can't think of any reason why this would happen in production only. Do you have any ideas on this? The code is the same and we're using the typical configuration used here: https://microsoft.github.io/durabletask-netherite/#/settings?id=typical-configuration

For reference, here is the development environment which was migrated about a month ago.

![image](https://user-images.githubusercontent.com/35069050/169485005-27c332f2-dce9-4d59-951d-2d6e8052a016.png)

**Comment by sebastianburckhardt** [comment]
Which version are you using? This is a known issue with releases prior to 1.0.0-rc1, because those did not properly track the size of the cache.

As of 1.0.0-rc1, we have a cache management policy that evicts instances when exceeding a threshold. This is not yet in the docs, but I can give you a quick description here.

Basically, each host reserves some amount of memory (default is 200 MB * processorCount) for instance and history state caching. So it would be normal for the cache to grow up to that limit.

You can set this _InstanceCacheSizeMB_ limit explicitly in host.json as you can see in [this example](https://github.com/microsoft/durabletask-netherite/blob/cb055b47e0fdc6dbde9346db1ca8eabec11336d9/test/PerformanceTests/host.json#L72).  

You can also check the DurableTaskPartitions table to see metrics on how much is in the cache. For each partition,  the column `CacheSizeMB` shows the current size of the cache. The column `CachePct` shows the percentage of available cache size that has been filled. Note that this percentage depends on how partitions are co-located. If all partitions are running on the same worker host, they have to share the available space, so each one gets less. If each partition is on a separate worker host, then each partition gets to use the full cache size.

**Comment by martinhenrysson** [comment]
It all makes sense then. I'm using 1.0.3 and have noticed the memory being released automatically after posting this issue.

Thanks a lot and great work!

**Comment by martinhenrysson** [comment]
Reopening this as the memory usage of our function doesn't seem to release memory after all. Maybe the drops in memory I saw were all caused by deployments or restarts. Not sure about that anymore, to be honest, but I was pretty sure at least one of the drops was automatic. The problem is that it's currently using over 2.0GB of memory.

![image](https://user-images.githubusercontent.com/35069050/171417189-c9f17b27-63ca-472f-8e4a-868397fb5e07.png)


Here is the DurableTaskPartitions table. Negative values for CacheMB and CachePct. Is that expected behavior?
![image](https://user-images.githubusercontent.com/35069050/171416797-f6ec4ce2-ddbd-4d11-9f4d-681dac8ef7f1.png)

**Comment by sebastianburckhardt** [comment]
The negative values are a known problem, we have an issue open for it (https://github.com/microsoft/durabletask-netherite/issues/132). It is not clear yet whether that is an independent problem, or the cause. I don't have a repro yet but will keep working on that.

Also, if you give me the appname and the Azure region, I can take a look at our internal telemetry to see if I can spot any anomalies.

**Comment by sebastianburckhardt** [comment]
You can contact me by e-mail (see contact info at the bottom left of my [homepage](https://www.microsoft.com/en-us/research/people/sburckha/)). 

What kind of plan and OS are you using?
