### ISSUE TITLE
Obtaining orchestrator status using the statusQueryGetUri which was set with SetCustomStatus intermittently hangs for a minute or more

### ISSUE THREAD

**Issue by ericleigh007** [microsoft/durabletask-netherite#241]
I have a PowerShell script that launches a function and then after that function returns its request status via `CreateCheckStatusResponse`, polls using the `statusQueryGetUri` endpoint.

For the default backend, if the poll period is set for 5 seconds, Powershell returns the status promptly without any noticeable delays.

Using Netherite, the status call eventually does return status, but it can hang for up to a minute prior to returning.

The PowerShell script is using `Invoke-WebRequest` to access the function's endpoint in both cases.

**Comment by sebastianburckhardt** [comment]
Instance status queries is one of the things where Netherite can be quite slow, unfortunately, in particular if this query happens at a moment where
- there is significant load on the task hub (such as while running a benchmark with lots of CPU or I/O load)
- the partition containing the instance is currently being relocated as a result of host shutdowns/failures/restarts.
- the partition containing the instance is currently being relocated as a result of scaling up or down the worker count 

Let me know if you think this explanation does not apply to your situtation. In that case I could take a look at the telemetry to see if there are any other reasons to explain the high latency.

FYI, the reason why Netherite latency for statusQueryGetUri  is fluctuating is because it has to go through a lot of steps:
- enqueues a message for the partition that owns the instance in the partitions event hub
- the worker node that hosts the partition pulls this message from event hubs
- the worker node looks up the instance state (possible accessing storage if the data is not in memory)
- the worker node sends the response message to the clients' event hub partition
- the client must pull the response message from event hubs

In comparison, the Azure Storage provider can often do all of this in a single Azure storage read, with much better latency.

**Comment by ericleigh007** [comment]
Thank you.
I would be glad to investigate some of this for the Microsoft Team.
I'm trying to get a good handle on whether/when Netherite scales out.  Perhaps there is a query/instructions for this that you can share.

On the whole, this is not a very important use case, but thanks very much for the explanation.  In case of production cases where Netherite is needed for sheer speed, it is good to know.

I'll leave this one open for a bit just to see if you want me to investigate my particular usage case to see what specifically causes the "hang".
