### ISSUE TITLE
Performance drop when using external events

### ISSUE THREAD

**Issue by lecamarade** [microsoft/durabletask-netherite#276]
Hi,

I'm testing Netherite and Azure Storage providers, to choose the best one for you workflow.

The setup:
Storage: 16 partitions
Netherite: 20 parititions
EP1  plan, concurrency activities and orchestrations 10/10.
Load 300K HelloCities5 runs.

When running [HelloCities](https://microsoft.github.io/durabletask-netherite/#/throughput) benchmark Netherite is faster.

However, the moment I add WaitForExternal event with a sub-orchestration, storage based function is ahead.

My questions is whether this is expected or not. Maybe you can explain how WaitForExternal event is implemented in Netherite?

Some details:

```
await context.CallSubOrchestratorAsync(nameof(SubOrchestrationExternalEvent), new StartExternalEventInput {InstanceId = context.InstanceId});
await context.WaitForExternalEvent<ExternalEventData>(Constants.HelloCitiesExternalEventName);
```

Benchmark results:

300K, No external event.
- Storage: 43min
- Netherite: 31min

300K,  WaitForExternalEvent
- Storage: 54min
- Netherite: 65min

**Comment by sebastianburckhardt** [comment]
This is not necessarily expected, no. If you can share the app name and the time window you used for these two tests, I can take a look at the internal telemetry and perhaps figure out what is going on.

**Comment by lecamarade** [comment]
Thank you, I'll log a support request. I wanted to make sure there was nothing in the architecture of Netherite that would explain it.

**Comment by sebastianburckhardt** [comment]
I have looked at the traces and one of the issues I am seeing is that there are issues with how RaiseEvent is currently implemented:

- it is inefficient because it actually performs two roundtrips to the partition (first calls GetInstanceState, then calls RaiseEvent)  instead of just one. This means it has high latency and wastes EH throughput.

- there is a consistency issue because the activity is using a client when calling RaiseEvent, and this client may see an older state (where the instance does not yet exist) because GetInstanceState may see a slightly stale instance state.

The best solution to both of those problems is to fix the internal implementation of RaiseEvent so it uses a single, strongly consistent round trip to the partition.

**Comment by cgillum** [comment]
@sebastianburckhardt can this issue be closed?

**Comment by sebastianburckhardt** [comment]
From what I understand this was fixed. Closing the issue.
