### ISSUE TITLE
Orchestrator start timed out when `PartitionManagement` is set to `ClientOnly`

### ISSUE THREAD

**Issue by shibayan** [microsoft/durabletask-netherite#287]
I added the `PartitionManagement` setting to `host.json` according to the Durable Functions Monitor settings, and now the orchestrator cannot be started.

https://github.com/microsoft/DurableFunctionsMonitor/tree/main/custom-backends/netherite

Specifically, the call to `StartNewAsync` will not complete and will eventually time out. This problem does not appear to occur in SingleHost mode, but only when using Event Hubs.

Netherite Version: 1.4.0

**Comment by sebastianburckhardt** [comment]
The symptoms you are seeing are consistent with no workers running for the task hub. 

Did you start any workers anywhere? There must be at least one host running with the default PartitionManagement (`EventProcessorHost`), otherwise there are no workers to execute the orchestrations.  The `ClientOnly` setting is meant to support creation of external clients, it does therefore not start any workers.

If you have workers running somewhere, another explanation could be that the configuration for the workers does not match the configuration for the client. Clients and workers must use the same task hub name and EH namespace.

**Comment by shibayan** [comment]
Thank you for your response. I now understand the `ClientOnly` setting.

I was trying various settings to use Netherite and Durable Functions Monitor, but I completely misunderstood what `ClientOnly` meant. The additional explanation has helped me understand more about the combination with the Durable Functions Monitor. 

Thank you.
