### ISSUE TITLE
Duplicate Activities Run Before First Has Finished

### ISSUE THREAD

**Issue by RichardBurns1982** [microsoft/durabletask-netherite#334]
We have put together a very simplistic example of a function (running in isolated net7) which scales out using Netherite and writes a simple entry to a database.  Within that activity it finds prime numbers to force CPU work and scale out. 

The example is included below:

```
[Function(nameof(NumberInstancesFunction_BeginOrchestration))]
public async Task<string> NumberInstancesFunction_BeginOrchestration(
    [OrchestrationTrigger] TaskOrchestrationContext context,
    CancellationToken cancellationToken = default)
{
    ILogger logger = context.CreateReplaySafeLogger(nameof(TestFunction));
    logger.LogInformation("Start processing.");

    var numberRange = _configuration.GetValue("NumberRange", 1000);
    var numbers = Enumerable.Range(1, numberRange).ToList();

    var groupId = Guid.NewGuid();
    var tasks = GetNumberExecutionTasks(context, groupId, numbers);
    await Task.WhenAll(tasks);

    logger.LogInformation("Done processing.");
    return "Completed";
}

private static IReadOnlyCollection<Task> GetNumberExecutionTasks(
  TaskOrchestrationContext context,
  Guid groupId,
  IReadOnlyCollection<int> numbers)
{
    return numbers.Select(x => context.CallActivityAsync(
            nameof(TestFunction_RunNumberActivity),
            input: new NumberRequest(groupId, x))).ToList();
}

[Function(nameof(TestFunction_RunNumberActivity))]
public async Task TestFunction_RunNumberActivity([ActivityTrigger] NumberRequest request, CancellationToken cancellationToken = default)
{
    var startedAt = DateTime.UtcNow;

    // Do some work
    var primNumbersToN = _configuration.GetValue("PrimNumbersToN", 10000);
    var result = Tasks.PrimeNumberTask.FindPrimeNumber(primNumbersToN);

    var numberInstance = new NumberInstance
    {
        GroupId = request.groupId,
        Number = request.number,
        StartedAt = startedAt,
        CompletedAt = DateTime.UtcNow,
    };
    _dataContext.NumberInstances.Add(numberInstance);

    await _dataContext.SaveChangesAsync(cancellationToken);
}
```

This simplistic example fans out on a range of numbers, say 1000, and runs an activity for each which writes a simple entry to a PostgresDb.  This is replicating an issue we are experiencing in production where the same activity is running multiple times in parallel causing duplicate data.  We write all our functions to be idempotent but this is very hard to do without a distributed lock if another activity instance runs the same message again before the first has finished.

We are seeing numerous examples with the code above where for the same groupid and number the second activity started at is before the first activity completed at:

|number|activity_1_started_at|activity_1_completed_at|activity_2_completed_at|activity_2_completed_at|
|---|---|---|---|---|
|298|2023-11-14 06:53:26.740 +0000|2023-11-14 06:53:41.512 +0000|2023-11-14 06:53:40.000 +0000|2023-11-14 06:53:44.537 +0000|
|224|2023-11-14 06:53:18.484 +0000|2023-11-14 06:53:50.589 +0000|2023-11-14 06:53:40.363 +0000|2023-11-14 06:53:49.867 +0000|
|223|2023-11-14 06:53:18.687 +0000|2023-11-14 06:53:50.780 +0000|2023-11-14 06:53:42.025 +0000|2023-11-14 06:53:52.160 +0000|
|221|2023-11-14 06:53:22.570 +0000|2023-11-14 06:53:52.323 +0000|2023-11-14 06:53:41.513 +0000|2023-11-14 06:53:55.452 +0000|
|222|2023-11-14 06:53:21.642 +0000|2023-11-14 06:53:53.527 +0000|2023-11-14 06:53:41.905 +0000|2023-11-14 06:53:55.965 +0000|

Host.json:

```
{
  "version": "2.0",
  "extensions": {
    "durableTask": {

      // The task hub name can be set explicitly
      "hubName": "rb-netherite-poc-1",

      // set this to true to reduce likelihood of duplicated work items   
      "UseGracefulShutdown": "true",

      // tweak these for performance tuning (work the same for all backends)
      "maxConcurrentActivityFunctions": "100",
      "maxConcurrentOrchestratorFunctions": "100",

      "storageProvider": {

        "type": "Netherite",

        // the number of partitions to use. Cannot be changed after task hub is created.
        "PartitionCount": "32",

        // where to look for the connection strings
        "StorageConnectionName": "AzureWebJobsStorage",
        "EventHubsConnectionName": "EventHubsConnection"
      }
    },
    "logging": {
      "applicationInsights": {
        "samplingSettings": {
          "isEnabled": true,
          "excludedTypes": "Request"
        }
      },
      "logLevel": {
        "default": "Warning"
      }
    }
  }
}
```

Would you expect us to be seeing the same message played before the first attempt has finished?  It's clear the first attempt has not failed as the entry has been saved to the DB so why is it being re-attempted at all.

We understand the documentation talks about at least once delivery with Netherite but would you expect that at least once delivery to happen before the first delivery has completed?

**Comment by sebastianburckhardt** [comment]
> Within that activity it finds prime numbers to force CPU work and scale out.

Cool. Sounds somewhat similar to a benchmark I am using myself. It is searching for hash collisions though, not prime numbers: https://github.com/microsoft/durabletask-netherite/tree/dev/test/PerformanceTests/Benchmarks/CollisionSearch

> We understand the documentation talks about at least once delivery with Netherite but would you expect that at least once delivery to happen before the first delivery has completed?

Unfortunately, yes. Duplicate concurrent executions are possible. For example, this happens if the runtime thinks that a first attempt has failed even if it has actually completed. The runtime then starts a new attempt even though the original attempt is not actually failed but just extremely slow for some reason (more on why this may be the case below). This "imperfect failure detection" is a fundamental problem in distributed systems, and not something we can completely prevent unfortunately.

That said, **it is not something we should see very often** when the system is working within a normal range of parameters.

Most likely, what is happening in your situation, is that the **CPU load is too high**. I have observed in my own benchmark that an extreme CPU load means that leases are not renewed in time (because all of the storage accesses are experiencing ridiculous delays in such situations). And if leases are not renewed in time, workers are deemed failed by the runtime, and restarted on other workers, which then leads to lots of duplicate work, matching the symptoms you are describing.

### Suggested Solution

The best way to fix this is to avoid extreme CPU loads, which can be done by limiting the number of activities that run at the same time on any given worker. There is a `host.json` configuration setting for that.

For my benchmark I adjusted the following setting
``` "maxConcurrentActivityFunctions": "10",```
which solved this problem for me. I suggest you try the same.

For CPU-bound activities my general recommendation would be to keep the number of concurrent activities below 2x the number of cores.
