### ISSUE TITLE
Durable Entities function do not automatically retry a failure message. But some times, we're seeing it retried

### ISSUE THREAD

**Issue by quangduyvo** [microsoft/durabletask-netherite#416]
Summary:
Now we don't know when a failure message will be automatically retried. 

Example: Automatically retried
+ Client signals an entity function failure due to GRPC being unavailable, but after a few seconds from a log we see this retried, the message is successfully delivered. 

Example: Don't automatically retry
+ When an exception throws at an entity function or anywhere in code, we don't see it retried.

Could you give me a certain situation when a failure message will be automatically retried? Thanks

**Comment by sebastianburckhardt** [comment]
These are the two behaviors:

- **When an exception is thrown by the application code of the entity**: the framework catches the exception and considers it to be the "result" of the operation. The entity state is rolled back to what it was before the operation started. If the entity was called from an orchestration, the exception is rethrown in the calling orchestration.

- **In any other error situations** (such as crashes, partition restarts, host restarts due to function timeouts, some out-of-memory errors, failure to access storage, etc.) the framework recovers the entity state prior to the delivery, and then tries to deliver the operation again.

**Comment by quangduyvo** [comment]
- **When an exception is thrown by the application code of the entity** => I've tested it and can confirm its state rolled back in this case

- **In any other error situations** => any other errors related to the system level will be retried that ensure at least one message delivery to the entity

Thank you for your help.  we can close this issue.
