### ISSUE TITLE
Storage exceptions preventing function execution on a regular basis

### ISSUE THREAD

**Issue by AlexanderHammer** [microsoft/durabletask-netherite#428]
Hello, 

we have 2 Functions with small states for handling IoT data and sending commands if required.
They both get triggered over Event Hub trigger and the entities get signaled only, and dont't start any orchestrations.
They pass their result to the system over Event Hubs
The plan has almost no ressource use and they handle around 500 messages per minute spreaded over all entities, some get any hardly messages over hours, some every 3 seconds.

Checkpoint: default values
Partitions: 32 for both at the beginning, now I switched one of them to 12
Plan:  EP2/EP Plan, min 4 instaces max 8; tried dedicated plans, hoped switching to EP would help with the issue
Project setup for both:

```
  <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <AzureFunctionsVersion>V4</AzureFunctionsVersion>
        <OutputType>Exe</OutputType>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>RandomNameSpace</RootNamespace>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="Microsoft.ApplicationInsights.WorkerService" Version="2.22.0" />
        <PackageReference Include="Microsoft.Azure.Functions.Worker" Version="1.22.0" />
        <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.DurableTask" Version="1.1.2" />
        <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.DurableTask.Netherite" Version="1.5.4" />
        <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.EventHubs" Version="6.3.1" />
        <PackageReference Include="Microsoft.Azure.Functions.Worker.Sdk" Version="1.17.2" />
        <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Http" Version="3.2.0" />
    </ItemGroup>
```

In our test env I never noticed/saw this issue, but on production after a few days of running or after Microsoft replaces one of the cluster instances, the functions grind to a halt, sometimes they manage to get out of it but it still takes an hour. 
Increasing the TU to 4 helped a little, but thats because the function for some reason decides to get all the messages from the event hub again for no apparent reason to me.
Very often I have to intervene by Hand, which is not feasable for 24/7 usage, and data loss due to "kicking" the function. 

Durable Event Hub view (12h):

![image](https://github.com/user-attachments/assets/f4b30fd0-6ae8-4be0-9e02-d4adcea32544)

After a long search I noticed, if there is no replacement of instances there happen storage failrues a few minutes before the functions act up. I scrolled down in the list to show some other failures other than creation of containers (12h view):

![image](https://github.com/user-attachments/assets/f1fd5101-39c3-467b-9e81-18f41516d2f1)

The only way  I managed to fix it, is killing the partition event hub, but often I need to kick the whole task, but lose all the state in the meantime and that is the only reason to use it. Both are on seperate storages, plans etc, I see the same happening. One of the functions just handles simple counter values and some handling code, so very small and very small messages coming in.

The Functionapp itself doesn't throw any exceptions or warnings, other than new instances have to get partition leases of the event hub which resolves itself quickly.  There is no exception beeing thrown as part of our code and it behaves itself for a while but then goes of the rails (30d view):

![image](https://github.com/user-attachments/assets/2e8a636a-99ad-4539-8068-e629d2bb2004)

Is netherite ready for this use case or do I have to move to a different way of handling small states?

*Edit, these issues also occures sometimes after deploying the function from Azure Dev Ops*

**Comment by TheBeveloper** [comment]
We're experiencing what looks like the same issue on our end on some of our instances. We've got >20 instances of function apps using Netherite running on production.

We can temporarily resolve this by changing our hub name.

## Affected Code
Alongside the blob errors we've also been hitting `Grpc.Core.RpcException` with the message:
`System.OperationCanceledException: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing`

The exceptions occur when these functions are called:
- `DurableTaskClient.ScheduleNewOrchestrationInstanceAsync`
- `DurableTaskClient.GetInstanceAsync`

## Information
### Setup
- `.NET Version`: .NET 8 isolated
- `(Netherite) PartitionCount`: 12
- `Runtime Version`: ~4
- `Platform`: 64bit

### Packages
- `Microsoft.Azure.Functions.Worker.Extensions.DurableTask.Netherite`: 2.1.0
- `Microsoft.Azure.Functions.Worker.Extensions.DurableTask`: 1.1.7

### Example Storage Failures
![Image](https://github.com/user-attachments/assets/13680369-db0f-4a09-9a2b-3caa9e11a37c)

## Stack Traces
[GetInstancesAsync_StackTrace.txt](https://github.com/user-attachments/files/17693210/GetInstancesAsync_StackTrace.txt)
[ScheduleNewOrchestrationInstanceAsync_StackTrace.txt](https://github.com/user-attachments/files/17693209/ScheduleNewOrchestrationInstanceAsync_StackTrace.txt)

**Comment by TheBeveloper** [comment]
Is there any update on this?

**Comment by AlexanderHammer** [comment]
I am going to close this issue at the end of the week, since I don't see any reaction and currently, when storage exceptions happen, they don't reinforce themselves anymore. 

I figure that reducing the partition count for the higher throughput entity helped with the issue, the other one still runs on 32 and does not have any major issues.

Here are pictures of the traffic for both EventHubs:

![Image](https://github.com/user-attachments/assets/0591b6d6-f646-494d-8130-8f4641d6d24a)


It looks like EventHub Checkpoints aren't beeing written, so everytime the function is beeing updated or restarted, it reads all the events from the last restart again, that creates much longer downtimes than it should from my pov. And stopping incoming events for minutes doesn't change anything, normal checkpoints are beeing written, but eventhub checkpoints are not beeing written it seems.

![Image](https://github.com/user-attachments/assets/71c5cdd8-481b-4c46-bf86-e8b95312381a)
