### ISSUE TITLE
tweak for the docs

### ISSUE THREAD

**Issue by ericsampson** [microsoft/durabletask-netherite#46]
I can't find the GH Pages or else I would have put this there (or made a PR), sorry :)

In the [Configuration section (Minimal)](https://microsoft.github.io/durabletask-netherite/#/settings?id=recommended-minimal-configuration), I think it would be worth adding the `PremiumStorageConnectionName` setting (commented out and described?) for discoverability.

Cheers!

**Comment by sebastianburckhardt** [comment]
Thanks for pointing this out! 

The reason why I didn't document it is because this setting is a bit experimental -- I did not mean for this to be used in a real environment. For example, you can only use this in combination with a regular storage account.

That said, I agree it makes more sense to just document what's there now.

**Comment by ericsampson** [comment]
Cool! I think it would be worth mentioning, even if it needs a callout like `// foo: experimental. blah`
Cheers :)

**Comment by sebastianburckhardt** [comment]
Added docs.
