### ISSUE TITLE
Netherite does not have setting to disable extended sessions

### ISSUE THREAD

**Issue by ConnorMcMahon** [microsoft/durabletask-netherite#78]
Netherite doesn't explicitly use extended sessions API, but it does provide similar behavior via cached cursors.

Durable Functions customers have a setting to disable extended sessions for performance reasons, and it would be nice if we could enforce this (i.e. in OrchestrationMessageBatch.OnReadComplete() check for extended sessions being disabled before using cached value.

This is likely a blocker for out-of-process Function apps, as they need to explicitly disable cursor based approaches like extended sessions to accommodate the out-of-proc algorithm.

**Comment by ConnorMcMahon** [comment]
Looks like this is discussed more in depth in #69, but I guess the ask here is to have the disableCursor setting respect extendedSessions, as we already have the infrastructure in place to automatically disable that for out-of-proc customers (and our testing infrastructure).

**Comment by sebastianburckhardt** [comment]
@ConnorMcMahon , do you think it would be possible to modify the `DurableTaskOptions` class so that the following settings are optional?

before:
  ```csharp
        public int ExtendedSessionIdleTimeoutInSeconds { get; set; }         
        public bool ExtendedSessionsEnabled { get; set; }
```
after:
  ```csharp
        public int? ExtendedSessionIdleTimeoutInSeconds { get; set; }         
        public bool? ExtendedSessionsEnabled { get; set; }
```

This would make it possible for backends to compute their own defaults, as opposed to having to abide by the existing defaults. Note that currently, this approach is already how we handle `MaxConcurrentOrchestratorFunctions` and `MaxConcurrentActivityFunctions`, where is also desirable to know whether a user wants to override the default or not.

**Comment by sebastianburckhardt** [comment]
Current plan is to keep the current setting called `CacheOrchestrationCursors`.
