### ISSUE TITLE
Support stand-alone client

### ISSUE THREAD

**Issue by sebastianburckhardt** [microsoft/durabletask-netherite#8]
Currently, clients can only be constructed as part of a full-featured OrchestrationService. However, there are situations in which it is desirable to run a client-only version, without executing orchestration steps or activities on that node, and without taking a dependency on the functions runtime.

For example, this can allow external clients to create orchestrations and retrieve their results without having to create an HttpTrigger just as a relay.

**Comment by ConnorMcMahon** [comment]
This is currently breaking a handful of tests in DurableFunctions that use the OrchestrationService as a client without calling .StartAsync() on it first (such as `ActorOrchestration_WithTaskHubName` and `ExternalEvents_WithTaskHubName_MultipleNamesLooping`).

It's worth noting that if you try to use the client without calling .StartAsync() path, the getter on the property `CheckedClient` nullrefs, because there was no startup exception.
